name: Análise Lighthouse

on:
  schedule:
    - cron: '0 0 * * 1' # Roda toda segunda-feira
  push:
    branches:
      - main

jobs:
  performance:
    name: Rodar Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Lighthouse CLI
        run: npm install -g lighthouse

      - name: Rodar Lighthouse no site
        run: |
          lighthouse http://gustavoverdi.github.io/Finance/ --output=json --output-path=./report.json --quiet --chrome-flags="--headless"

      - name: Armazenar relatório como artefato
        uses: actions/upload-artifact@v2  # Atualizado para v2
        with:
          name: lighthouse-report
          path: ./report.json
