name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Verificar Código
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Instalar ESLint
        run: npm install -g eslint
      
      - name: Verificar JavaScript
        run: eslint scripts.js || true
      
      - name: Verificar PHP
        run: |
          sudo apt-get install php-cli
          php -l cadastro.php || true
          php -l login.php || true
  
  deploy:
    name: Deploy no GitHub Pages
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3
      
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v2
      
      - name: Fazer deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
